version: "3.8"

services:
  frontend:
    image: 315761229905.dkr.ecr.eu-north-1.amazonaws.com/docker-frontend-db
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - network-backend

  backend:
    image: 315761229905.dkr.ecr.eu-north-1.amazonaws.com/docker-backend-db
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://username:password@mongo:27017
    networks:
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    networks: 
      - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
