Luiza
Add Status

Luiza — 8:11 PM
name: Deploy Docker Compose App to EC2
hosts: all
become: yes

  vars:
    aws_region: eu-north-1
    ecr_repo_url: 315761229905.dkr.ecr.eu-north-1.amazonaws.com

  tasks:
    
name: Install required packages
    apt:
      name:
docker.io
docker-compose
awscli
update_cache: yes
state: present

    
name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
name: Login to ECR
shell: |
  aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ ecr_repo_url }}
environment:
  AWS_REGION: "{{ aws_region }}"
name: Copy docker-compose.yml
copy:
  src: ../docker-compose.yml
  dest: /home/ubuntu/docker-compose.yml
  owner: ubuntu
  group: ubuntu
  mode: 0644

name: Deploy app with docker-compose
become_user: ubuntu
shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
Վառլեն — 8:14 PM
name: Deploy Docker Compose App to EC2
hosts: all
become: yes

  vars:
    aws_region: eu-north-1
    ecr_repo_url: 315761229905.dkr.ecr.eu-north-1.amazonaws.com

  tasks:
    
name: Install Docker
    apt:
      name: docker.io
      state: present
      update_cache: yes

    
name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: '0755'

    
name: Install unzip (needed for AWS CLI)
    apt:
      name: unzip
      state: present

    
name: Download AWS CLI v2
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp/awscliv2.zip

    
name: Unzip AWS CLI installer
    unarchive:
      src: /tmp/awscliv2.zip
      dest: /tmp
      remote_src: yes

    
name: Install AWS CLI v2
    command: /tmp/aws/install --update
    args:
      creates: /usr/local/bin/aws

    
name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

    
name: Login to ECR
    shell: |
      aws ecr get-login-password --region {{ aws_region }} | \
      docker login --username AWS --password-stdin {{ ecr_repo_url }}

    
name: Copy docker-compose.yml
    copy:
      src: ../docker-compose.yml
      dest: /home/ubuntu/docker-compose.yml
      owner: ubuntu
      group: ubuntu
      mode: '0644'

    
name: Deploy app with Docker Compose
    become_user: ubuntu
    shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
- name: Deploy Docker Compose App to EC2
  hosts: all
  become: yes

  vars:
    aws_region: eu-north-1
Expand
BDG SEND.txt
2 KB
﻿
Վառլեն
varlen_grigoryan
- name: Deploy Docker Compose App to EC2
  hosts: all
  become: yes

  vars:
    aws_region: eu-north-1
    ecr_repo_url: 315761229905.dkr.ecr.eu-north-1.amazonaws.com

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Install unzip (needed for AWS CLI)
      apt:
        name: unzip
        state: present

    - name: Download AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI v2
      command: /tmp/aws/install --update
      args:
        creates: /usr/local/bin/aws

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | \
        docker login --username AWS --password-stdin {{ ecr_repo_url }}

    - name: Copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Deploy app with Docker Compose
      become_user: ubuntu
      shell: docker-compose -f /home/ubuntu/docker-compose.yml up -d
