name: Build and Scan Docker Images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend Docker image
      run: docker build -t backend-image:latest ./backend

    - name: Build frontend Docker image
      run: docker build -t frontend-image:latest ./frontend

    - name: Scan backend Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: backend-image:latest
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH

    - name: Scan frontend Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: frontend-image:latest
        format: table
        exit-code: 0
        severity: CRITICAL,HIGH
